language: node_js

node_js:
  - "5"

notifications:
  # disable email notification
  email: false

services:
  - mongodb

install:
  - curl https://install.meteor.com | /bin/sh

script:
  # remove unused node modules from cache
  - rm -rf node_modules
  - npm install -g tslint@3.15.1 typescript@2.0.6 rollup@0.36.3 yarn
  - yarn
  - npm run test:ci

sudo: required
