language: node_js

node_js:
  - "5"

cache:
  directories:
    # cache node modules
    - node_modules

notifications:
  # disable email notification
  email: false

services:
  - mongodb

install:
  - curl https://install.meteor.com | /bin/sh

script:
  # remove unused node modules from cache
  - npm prune
  - npm install -g typings tslint typescript
  - npm run test:ci

sudo: required
